/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `badepiv10_mrc_classe`;
CREATE TABLE `badepiv10_mrc_classe` (
  `NO_PROCESS` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `CD_CLASSE_NICE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `REV_CLASSE_NICE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `ST_CLASSE_NICE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

DROP TABLE IF EXISTS `badepiv10_mrc_depositante`;
CREATE TABLE `badepiv10_mrc_depositante` (
  `NO_PROCESS` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `CD_TIPO_PFPJ` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `NO_CNPJ_CPF` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `NM_COMPLET_PFPJ` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `CD_PAIS_PFPJ` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `CD_UF_PFPJ` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `NM_CIDADE_PFPJ` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `CD_IBGE_CIDADE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

DROP TABLE IF EXISTS `badepiv10_mrc_deposito`;
CREATE TABLE `badepiv10_mrc_deposito` (
  `NO_PROCESS` int DEFAULT NULL,
  `TP_ENTRADA` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `DT_DEPOSIT_PROCESS` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `DT_ENTRADA_INPI` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `CD_NATUREZ_MARCA` int DEFAULT NULL,
  `DS_NATUREZ_MARCA` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `CD_APRESEN_MARCA` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

DROP TABLE IF EXISTS `badepiv10_mrc_despacho`;
CREATE TABLE `badepiv10_mrc_despacho` (
  `NO_PROCESS` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `CD_DESPACH` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `NO_RPI` int DEFAULT NULL,
  `DT_PUBLICACAO` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `CD_SITUACAO_NV` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci,
  `NO_PROTOCOLO` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;